### ISSUE TITLE
DinD support

### ISSUE THREAD

**Issue by yunspace** [flemay/docker-musketeers#1]
Hey @flemay good work on all the various 3musketeers related projects.

Just wanted to point out `docker-3musketeers` seems to be lacking a major ingredient, which is `docker`. Or precisely docker in docker (dind). For use cases such as GitLabCI or BitBucket pipelines where I want to run something like:

```
image: flemay/3muksteers:dind

# overlay2 provides improved performance for dind
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - make test
```

What you think? Currently I'm working around this by using the following:

```
image: docker:stable

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - apk add --no-cache make
```

But it would be much more preferable to use the official 3musketters image!
